---
title: 7. 오류 처리
draft: false
tags:
---
> [!NOTE]
> 아는만큼 보인다...😭

오류 처리는 프로그램에 반드시 필요한 요소 중 하나이다.
코드에서 뭔가 잘못된 것이 있으면 그것을 바로 잡을 책임은 바로 우리 프로그래머에게 있다.
하지만 오류 처리 코드로 인해 프로그램 논리를 이해하기 어려워진다면 깨끗한 코드라 부르기 어렵다.

## 오류 코드보다 예외를 사용하라
- 과거에는 예외를 지원하지 않는 프로그래밍 언어가 많았고, 오류 플래그를 설정하거나 오류 코드를 반환하는 방법을 사용했다.
	- 아래와 같은 방법을 사용하면 호출자 코드가 복잡해진다.
```java
public class DeviceController { ...

public void sendShutDown() { 
	DeviceHandle handle = getHandle(DEV1); 
	// Check the state of the device  
	if (handle != DeviceHandle.INVALID) {
	
		// Save the device status to the record field 
		retrieveDeviceRecord(handle);
		
		// If not suspended, shut down  
		if (record.getStatus() != DEVICE_SUSPENDED) {

			pauseDevice(handle); 
			clearDeviceWorkQueue(handle); 
			closeDevice(handle);

		} else {  
			logger.log("Device suspended. Unable to shut down");

		}  
	} else {
		logger.log("Invalid handle for: " + DEV1.toString()); }
	}

	... 
}
```
- 예외를 던지는 방식을 사용하면 호출자 코드가 더 깔끔해진다.
```java
public class DeviceController { 
	...

	public void sendShutDown() { 
		try {
			tryToShutDown();  
		} catch (DeviceShutDownError e) {
			logger.log(e); 
		}
	}
	private void tryToShutDown() throws DeviceShutDownError { 
		DeviceHandle handle = getHandle(DEV1);  
		DeviceRecord record = retrieveDeviceRecord(handle);

		pauseDevice(handle); 
		clearDeviceWorkQueue(handle); 
		closeDevice(handle);
	}

	private DeviceHandle getHandle(DeviceID id) { 
		...
		throw new DeviceShutDownError("Invalid handle for: " + id.toString());
		... 
	}	
	... 
}
```
## Try-Catch-Finally 문부터 작성하라
- try 블록에 들어가는 코드를 실행하면 어느 시점에서든 실행이 중단된 후 catch 블록으로 넘어갈 수 있다.
- try 블록은 트랜젝션과 비슷하다. try 블록에서 무슨 일이 생기든지 catch 블록은 프로그램 상태를 일관성 있게 유지해야 한다.

## 미확인 예외를 사용하라
- 확인된 예외는 OCP(Open Closed Principle)를 위반한다.

> [!NOTE]
> checked exception : 잘못된 코드가 아닌 잘못된 상황에서 발생하는 예외, 예외처리가 없을 경우 컴파일 에러 발생 - catch 또는 throws 로 처리를 반드시 해야한다.
> unchecked exception : RuntimeException, 잘못 구현된 코드로 발생하는 예외

-> 예외처리를 강제하지 말라는 것인가?

- 하위 단계에서 코드를 변경하면 상위 단계 메서드 선언부를 전부 고쳐야하는 문제가 발생한다.
- 
```java
 public void printA(bool flag) {
     if(flag)
         System.out.println("called");
 }

 public void func(bool flag) {
     printA(flag);
 }
 ```
 
```java
 public void printA(bool flag) throws NotPrintException {
     if(flag)
         System.out.println("called");
     else
         throw new NotPrintException();
 }

 public void func(bool flag) throws NotPrintException {
     printA(flag);
 }
 ```
## 예외에 의미를 제공하라
- 예외를 던질 때는 전후 상황을 충분히 덧붙인다.
	- 호출 스택 뿐만아니라 실패한 연산 이름과 실패 유형도 언급한다.
	- 애플리케이션이 로깅 기능을 사용한다면 catch 블록에서 오류를 기록하도록 충분한 정보를 넘겨준다.

## 호출자를 고려해 예외 클래스를 정의하라
- 외부 API 와 Exception 유형을 wrapping(감싸기 기법) 을 이용해서 의존성을 줄인다. 

## 정상 흐름을 정의하라
- 앞절의 지침을 충실히 이행하면 비즈니스 논리와 오류처리가 잘 분리된 코드가 나온다.
- 정상 로직을 불필요한 Exception 으로 정의하지 마라.
	- 코드를 이해하기 어렵고, 불필요하다.

## null을 반환하지 마라
- null 을 반환하는 코드는 일거리를 늘릴 뿐만 아니라 호출자에게 문제를 떠넘긴다.
- 누구 하나라도 null 확인을 빼먹는다면 애플리케이션이 통제 불능에 빠질지도 모른다.
- null 을 반환하고픈 유혹이 든다면 예외를 던지거나 특수사례 객체를 반환하라.

## null을 전달하지 마라
- 메서드로 null 을 전달하는 방식은 더 나쁘다.
- 정상적인 인수로 null 을 기대하는 api 가 아니라면 메서드로 null 을 전달하는 코드는 최대한 피한다.
- 그렇다면 request 에서 들어오는 값은 어떻게 핸들링 해야할까? notNull 어노테이션을 쓰고 익셉션 핸들링?


## 리팩토링
### 원본 코드

```java
@Override  
protected void processSyncData(KcaNewsResult result) {  
  
    for (KcaNewsResult.KcaNews kcaNews : result.getData()) {  
  
        // 파일 생성  
        FileMasterDto.SimpleDto fileMaster = createFileMaster(kcaNews);  
        if (fileMaster == null) {  
            log.error(kcaNews.toString());  
            log.error("Find or Create FileMaster failed. skip");  
            continue;  
        }  
  
        KcaNewsResult.KcaNewsConverter kcaNewsConverter = new KcaNewsResult.KcaNewsConverter(kcaNews, fileMaster);  
  
        // parentCategoryDto 검색  
        CategoryDto parentCategoryDto = findCategoryDto(kcaNewsConverter);  
  
        KcaFaqPersistDtoConverterBase.ConvertEntity convertEntity = kcaNewsConverter.convert(parentCategoryDto);  
  
        if (convertEntity.isValid()) {  
            kcaFaqService.createOrUpdateKcaFaq(convertEntity.getKcaFaqPersistDto());  
        }  
    }  
}  
  
private FileMasterDto.SimpleDto createFileMaster(KcaNewsResult.KcaNews kcaNews) {  
    KcaSharedFileMasterPersistDto persistDto = KcaSharedFileMasterPersistDto.builder()  
            .fileName(kcaNews.getFileName())  
            .directory(kcaNews.getFilePath())  
            .savedName(kcaNews.getFileSname())  
            .fileType(FileType.DOCUMENT)  
            .build();  
  
        try {  
            return kcaSharedFileManagerService.createFileMaster(persistDto);  
        } catch (Exception e) {  
            e.printStackTrace();  
        }  
        return null;  
}
```
#### 문제점
- createFileMaster 메소드가 null 을 반환할 수 있다.
- createFileMaster 메소드에서 오류를 형편없이 분류했다. (Exception 을 상속받는 모든 오류는 동일하게 처리하도록) -> 사실 어떤 사유에서든 메서드가 정상적으로 동작하지 않는다면 뒷 작업을 스킵하게 하기 위한 의도였다.
- 예외에 의미를 제공하지 않았다. (사실 뒷 로직에 예외로그가 따로 존재함)

### 수정
```java
@Override  
protected void processSyncData(KcaNewsResult result) {  
  
    for (KcaNewsResult.KcaNews kcaNews : result.getData()) {  
  
        // 파일 생성  
        FileMasterSimpleDtoWrapper wrapper = createFileMaster(kcaNews);  
        if (!wrapper.isValid) {  
            continue;  
        }  
  
        KcaNewsResult.KcaNewsConverter kcaNewsConverter = new KcaNewsResult.KcaNewsConverter(kcaNews, wrapper.getDto());  
  
        // parentCategoryDto 검색  
        CategoryDto parentCategoryDto = findCategoryDto(kcaNewsConverter);  
  
        KcaFaqPersistDtoConverterBase.ConvertEntity convertEntity = kcaNewsConverter.convert(parentCategoryDto);  
  
        if (convertEntity.isValid()) {  
            kcaFaqService.createOrUpdateKcaFaq(convertEntity.getKcaFaqPersistDto());  
        }  
    }  
}  
  
private FileMasterSimpleDtoWrapper createFileMaster(KcaNewsResult.KcaNews kcaNews) {  
    KcaSharedFileMasterPersistDto persistDto = KcaSharedFileMasterPersistDto.builder()  
            .fileName(kcaNews.getFileName())  
            .directory(kcaNews.getFilePath())  
            .savedName(kcaNews.getFileSname())  
            .fileType(FileType.DOCUMENT)  
            .build();  
    boolean isValid = true;  
        FileMasterDto.SimpleDto fileMaster = null;  
        try {  
             fileMaster= kcaSharedFileManagerService.createFileMaster(persistDto);  
        } catch (Exception e) {  
            log.error(kcaNews.toString());  
            log.error("Find or Create FileMaster failed. skip");  
            e.printStackTrace();  
            isValid = false;  
        }  
        return new FileMasterSimpleDtoWrapper(isValid, fileMaster);  
}

@AllArgsConstructor  
@Getter  
public static class FileMasterSimpleDtoWrapper {  
    private boolean isValid;  
    private FileMasterDto.SimpleDto dto;  
}
```

#### 변경점
- dto 와 isvalid 를 감싸는 wrapper 를 생성해서 null 발생 가능성을 낮추었다.
- catch 절에서 에러를 좀 더 디테일하게 변경했다.
- 오류를 형편없이 분류한건 의도상 그대로 두어버렸다.

### 주절주절
web api 프로젝트에서 null 이나 empty 를 검사하는 로직을 전혀 안쓰기는 어려울 것 같다. (사용자가 null 값을 전달할 수 있기 때문에)


https://amazingguni.github.io/blog/2016/05/Clean-Code-7-%EC%98%A4%EB%A5%98-%EC%B2%98%EB%A6%AC
https://velog.io/@lychee/Clean-Code-7%EC%9E%A5-%EC%98%A4%EB%A5%98-%EC%B2%98%EB%A6%AC